---
- name: assert | Test if chrony_role_action is defined
  ansible.builtin.assert:
    that:
      - chrony_role_action is defined
      - chrony_role_action is string
      - chrony_role_action in [
        "all", "requirements", "install", "configure", "logrotate", "upgrade",
        "test"
        ]
    quiet: true

- name: assert | Test if chrony_service_enabled is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_service_enabled is defined
      - chrony_service_enabled is boolean
    quiet: true

- name: assert | Test if chrony_configure_logrotate is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_configure_logrotate is defined
      - chrony_configure_logrotate is boolean
    quiet: true

- name: assert | Test if chrony_logrotate_options is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_logrotate_options is defined
    quiet: true
  when: >
    chrony_configure_logrotate | default(false)

- name: assert | Test if chrony_as_ntp_server is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_as_ntp_server is defined
      - chrony_as_ntp_server is boolean
    quiet: true

- name: assert | Test if chrony_global_server_settings is defined and set
    correctly
  ansible.builtin.assert:
    that:
      - chrony_global_server_settings is defined
      - chrony_global_server_settings is string
    quiet: true

- name: assert | Test if chrony_ntp_servers is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_ntp_servers is defined
      - chrony_ntp_servers is iterable
    quiet: true

- name: assert | Test if chrony_global_pool_settings is defined and set
    correctly
  ansible.builtin.assert:
    that:
      - chrony_global_pool_settings is defined
      - chrony_global_pool_settings is string
    quiet: true

- name: assert | Test if chrony_rtc_settings is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_rtc_settings is defined
      - chrony_rtc_settings is iterable
    quiet: true

- name: assert | Test if chrony_bind_addresses is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_bind_addresses is defined
      - chrony_bind_addresses is iterable
    quiet: true

- name: assert | Test if chrony_makestep_args is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_makestep_args is defined
      - chrony_makestep_args is string
    quiet: true

- name: assert | Test if chrony_num_minsources is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_num_minsources is defined
    quiet: true

- name: assert | Test if chrony_leapsectz_settings is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_leapsectz_settings is defined
      - chrony_leapsectz_settings is string
    quiet: true

- name: assert | Test if chrony_logdir_path is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_logdir_path is defined
      - chrony_logdir_path is string
    quiet: true

- name: assert | Test if chrony_logged_information is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_logged_information is defined
      - chrony_logged_information is string
    quiet: true

- name: assert | Test if chrony_ntp_clients is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_ntp_clients is defined
      - chrony_ntp_clients is iterable
    quiet: true
