---
- name: assert | Test if chrony_role_action is defined 
  ansible.builtin.assert:
    that:
      - chrony_role_action is defined
      - chrony_role_action is string
      - chrony_role_action in [
        "all", "requirements", "install", "configure", "logrotate", "upgrade",
        "test"
        ]
    quiet: true

- name: assert | Test if chrony_service_enabled is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_service_enabled is defined
      - chrony_service_enabled is boolean
    quiet: true

- name: assert | Test if chrony_configure_logrotate is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_configure_logrotate is defined
      - chrony_configure_logrotate is boolean
    quiet: true

- name: assert | Test if chrony_logrotate_options is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_logrotate_options is defined
    quiet: true
  when: >
    chrony_configure_logrotate | default(false)

- name: assert | Test if chrony_ntp_source_mode is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_ntp_source_mode is defined
      - chrony_ntp_source_mode in [ "pool", "server" ]
    fail_msg: "'chrony_ntp_source_mode' must be 'pool' or 'server"
    quiet: true

- name: assert | Test if chrony_ntp_servers is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_ntp_servers is defined
      - chrony_ntp_servers is iterable
    quiet: true

- name: assert | Test if chrony_rtcsync_enable is defined and set
    correctly
  ansible.builtin.assert:
    that:
      - chrony_rtcsync_enable is defined
      - chrony_rtcsync_enable is boolean
    quiet: true

- name: assert | Test if chrony_maxdistance is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_maxdistance is defined
    quiet: true

- name: assert | Test if chrony_ntsdumpdir is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_ntsdumpdir is defined
      - chrony_ntsdumpdir is string
    quiet: true

- name: assert | Test if chrony_num_minsources is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_num_minsources is defined
      - chrony_num_minsources is number
    quiet: true

- name: assert | Test if chrony_maxupdateskew is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_maxupdateskew is defined
    quiet: true

- name: assert | Test if chrony_makestep is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_makestep is defined
    quiet: true

- name: assert | Test if chrony_logchange is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_logchange is defined
    quiet: true

- name: assert | Test if chrony_leapsectz is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_leapsectz is defined
      - chrony_leapsectz is string
    quiet: true

- name: assert | Test if chrony_log_enable is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_log_enable is defined
      - chrony_log_enable is boolean
    quiet: true

- name: assert | Test if chrony_logdir_path is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_logdir_path is defined
      - chrony_logdir_path is string
    quiet: true

- name: assert | Test if chrony_log_options is defined and set correctly
  ansible.builtin.assert:
    that:
      - chrony_log_options is defined
      - chrony_log_options is string
    quiet: true
