---
# =============================================================================
# Ansible Role: Chrony - Log Rotation Configuration
# =============================================================================
# This file contains tasks for configuring log rotation for Chrony logs.
# It ensures proper log file management and rotation settings.
#
# Sections:
#   1. Archive Directory Management
#   2. Logrotate Configuration Deployment
# =============================================================================

# -----------------------------------------------------------------------------
# 1. Archive Directory Management
# -----------------------------------------------------------------------------
- name: logrotate | Check whether the archive log directory exists
  ansible.builtin.stat:
    path: "{{ chrony_logrotate_options.archive_directory_path  }}"
  register: _archive_log_directory_stat_
  changed_when: false
  failed_when: false
  become: true

- name: logrotate | Create archive log directory if does not exists
  ansible.builtin.file:
    path: "{{ chrony_logrotate_options.archive_directory_path }}"
    state: directory
    mode: "0755"
  when: >
    not _archive_log_directory_stat_.stat.exists
  become: true

# -----------------------------------------------------------------------------
# 2. Logrotate Configuration Deployment
# -----------------------------------------------------------------------------
- name: logrotate | Deploy logrotate config file
  ansible.builtin.template:
    src: "templates/logrotate/chrony.j2"
    dest: "{{ chrony_logrotate_config_path }}"
    owner: root
    mode: "0644"
  become: true
