---
- name: chrony | include_vars | Gather OS specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts['distribution'] | lower }}_{{ ansible_facts['distribution_version'] | lower }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}_{{ ansible_facts['distribution_major_version'] | lower }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}_{{ ansible_facts['distribution_version'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}_{{ ansible_facts['distribution_major_version'].split('.')[0] }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
        - "main.yml"
      paths:
        - "{{ role_path }}/vars"
  tags:
    - always
    - vars

- name: chrony | assert | Perform Conditional Tasks
  import_tasks: assert.yml
  run_once: true
  delegate_to: localhost
  tags:
    - always
    - asserts

- name: chrony | requirements | Make sure that system meets requirements
  include_tasks: requirements.yml
  when: >
    chrony_role_action in ['all', 'requirements']
  tags:
    - always
    - requirements

- name: chrony | install | Install chrony package
  include_tasks: install.yml
  when: >
    chrony_role_action in ['all', 'install']
  tags:
    - always
    - install

- name: chrony | configure | Configure chrony service
  include_tasks: configure.yml
  when: >
    chrony_role_action in ['all', 'configure']
  tags:
    - always
    - configure

- name: chrony | logrotate | Configure logrotate for chrony service
  include_tasks: logrotate.yml
  when: >
    chrony_role_action in ['all', 'configure', 'logrotate'] and
    chrony_configure_logrotate | default(false)
  tags:
    - always
    - configure
    - logrotate

- name: chrony | upgrade | Upgrade chrony package
  include_tasks: upgrade.yml
  when: >
    chrony_role_action in ['upgrade']
  tags:
    - always
    - upgrade

- name: chrony | test | Make sure that time is synchronized with server
  include_tasks: test.yml
  when: >
    chrony_role_action in ['all', 'configure', 'upgrade', 'test']
  tags:
    - always
    - configure
    - upgrade
    - test
