---
- name: test | Flush handlers
  meta: flush_handlers

- name: test | Force NTP sync
  become: true
  ansible.builtin.command: chronyc makestep
  changed_when: false

- name: test | Ensure system is NTP time synced
  ansible.builtin.command: chronyc waitsync 30
  changed_when: false
