---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Check if chrony is installed
      ansible.builtin.package:
        name: "{{ chrony_package_name }}"
        state: present
      check_mode: true

    - name: Check if chrony service is running and enabled
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: true
      check_mode: true

    - name: Check chrony configuration file
      ansible.builtin.stat:
        path: /etc/chrony.conf
        checksum_algorithm: sha256
      register: chrony_conf
      check_mode: true

    - name: Verify chrony is working
      ansible.builtin.command: chronyc tracking
      register: chrony_tracking
      changed_when: false
      check_mode: true
