---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rocky9
    image: rockylinux:9
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cgroupns_mode: host
    pre_build_image: true
    env:
      ANSIBLE_PYTHON: /usr/bin/python3

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  config_options:
    defaults:
      interpreter_python: /usr/bin/python3
  env:
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_VERBOSITY: 2

verifier:
  name: ansible
  options:
    verbose: true
