---
- name: molecule | Converge
  hosts: all

  pre_tasks:

    - name: Converge | Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: >
        ansible_os_family == "Debian"

    - name: Converge | Update dnf cache
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false
      when: >
        ansible_os_family == "RedHat"

    - name: Converge | Wait for systemd to complete initialization
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: >
        ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

  roles:

    - role: grzegorzfranus.chrony
