---
- name: molecule | Prepare
  hosts: all
  gather_facts: true

  tasks:

    - name: Prepare | Update apt cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: >
        ansible_os_family == "Debian"

    - name: Prepare | Update dnf cache
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false
      when: >
        ansible_os_family == "RedHat"

    - name: Prepare | Install sudo package
      ansible.builtin.package:
        name: sudo
        state: present
