---
- name: molecule | Prepare
  hosts: all
  gather_facts: true

  tasks:

    # - name: Prepare | Update apt cache
    #   ansible.builtin.apt:
    #     update_cache: true
    #   changed_when: false
    #   when: >
    #     ansible_os_family == "Debian"

    # - name: Prepare | Update dnf cache
    #   ansible.builtin.dnf:
    #     update_cache: true
    #   changed_when: false
    #   when: >
    #     ansible_os_family == "RedHat"

    - name: Prepare | Configure sudo for testing
      ansible.builtin.copy:
        content: |
          Defaults !requiretty
          %wheel ALL=(ALL) NOPASSWD: ALL
        dest: /etc/sudoers.d/wheel
        mode: '0440'
      become: true

    - name: Prepare | Ensure wheel group exists
      ansible.builtin.group:
        name: wheel
        state: present
      become: true

    - name: Prepare | Add ansible user to wheel group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: wheel
        append: yes
      become: true

    - name: Prepare | Install python3.12 package
      ansible.builtin.package:
        name: "python3.12"
        state: present
      become: true

    - name: Prepare | Ensure /usr/bin/python points to python3.12
      ansible.builtin.file:
        src: /usr/bin/python3.12
        dest: /usr/bin/python
        state: link
        force: true
      become: true

    - name: Prepare | Set Python alternatives
      ansible.builtin.command: >
        alternatives --install /usr/bin/python python /usr/bin/python3.12 100
      changed_when: false
      become: true

    - name: Prepare | Select Python 3.12 as default
      ansible.builtin.command: >
        alternatives --set python /usr/bin/python3.12
      changed_when: false
      become: true
