---
- name: molecule | Verify Role
  hosts: all

  vars_files:
    - ../../defaults/main.yml

  tasks:

    - name: Verify | Gather OS specific variables
      include_vars: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files:
            - "{{ ansible_facts['distribution'] | lower }}_{{ ansible_facts['distribution_version'] | lower }}.yml"
            - "{{ ansible_facts['distribution'] | lower }}_{{ ansible_facts['distribution_major_version'] | lower }}.yml"
            - "{{ ansible_facts['distribution'] | lower }}.yml"
            - "{{ ansible_facts['os_family'] | lower }}_{{ ansible_facts['distribution_version'] | lower }}.yml"
            - "{{ ansible_facts['os_family'] | lower }}_{{ ansible_facts['distribution_major_version'].split('.')[0] }}.yml"
            - "{{ ansible_facts['os_family'] | lower }}.yml"
            - "main.yml"
          paths:
            - "../../vars"

    - name: Verify | Check if chrony package is installed
      ansible.builtin.package:
        name: chrony
        state: present
      check_mode: true

    - name: Verify | Check if installed binary is available
      ansible.builtin.command: chronyc --version
      register: _version_result_
      changed_when: false
      failed_when: _version_result_.rc != 0

    - name: Verify | Show check version details
      ansible.builtin.debug:
        msg: >
          Version Output:
          {{ _version_result_.stdout_lines | join('\n') }}

    - name: Verify | Check if chrony service is running
      ansible.builtin.service:
        name: "{{ chrony_service_name }}"
        state: started
      check_mode: true

    - name: Verify | Check chrony configuration file exists
      ansible.builtin.stat:
        path: "{{ chrony_config_path }}"
      check_mode: true

    - name: Verify | Check chrony synchronization
      ansible.builtin.shell: |
        chronyc tracking
      changed_when: false
      check_mode: true
