name: Molecule Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - rocky9
          - debian12
        # python-version: ['3.9', '3.10', '3.11']
        python-version: ['3.11']

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule molecule-docker ansible-lint yamllint

      # - name: Run Ansible Lint
      #   run: ansible-lint

      - name: Run YAML Lint
        run: yamllint .

      - name: Run Molecule Test
        run: molecule test -s ${{ matrix.scenario }}
        env:
          MOLECULE_NO_LOG: false

      # - name: Run Security Scan
      #   uses: snyk/actions/python@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     args: --severity-threshold=high

      # - name: Upload Test Results
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: molecule-results-${{ matrix.scenario }}-${{ matrix.python-version }}
      #     path: |
      #       .molecule/
      #       molecule-results/
